name: app
description: "A pet project for a test assignment on implementing push notifications."
version: 0.0.1
environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # notifications
  firebase_messaging: ^15.2.5
  firebase_core: ^3.13.0
  flutter_local_notifications: ^19.0.0

  # router
  auto_route: ^9.3.0

  # Freezed
  freezed_annotation: ^2.4.4
  freezed: ^2.5.2

  # DI
  get_it: ^8.0.3
  injectable: ^2.5.0
  injectable_generator: ^2.6.2

  # Bloc
  flutter_bloc: ^9.0.0

  # UI
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
